import { Component } from '@angular/core';

import { Card } from './card.model';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'ToDo list';
  item = '';
  items: string[] = [];

  cards: Card[] = [
    {
      name: "Ancestor's Chosen",
      color: 'White',
      type: 'Creature — Human Cleric',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: "First strike (This creature deals combat damage before creatures without first strike.)\nWhen Ancestor's Chosen enters the battlefield, you gain 1 life for each card in your graveyard.",
      artist: 'Pete Venters',
      number: '1',
      price: 550,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=130550&type=card',
      id: '5f8287b1-5bb6-5f4c-ad17-316a40d5bb0c',
    },
    {
      name: 'Angel of Mercy',
      color: 'White',
      type: 'Creature — Angel',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: 'Flying\nWhen Angel of Mercy enters the battlefield, you gain 3 life.',
      artist: 'Volkan Baǵa',
      number: '2',
      price: 465,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129465&type=card',
      id: '57aaebc1-850c-503d-9f6e-bb8d00d8bf7c',
    },
    {
      name: 'Aven Cloudchaser',
      color: 'White',
      type: 'Creature — Bird Soldier',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: "Flying (This creature can't be blocked except by creatures with flying or reach.)\nWhen Aven Cloudchaser enters the battlefield, destroy target enchantment.",
      artist: 'Justin Sweet',
      number: '7',
      price: 470,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129470&type=card',
      id: '8ac972b5-9f6e-5cc8-91c3-b9a40a98232e',
    },
    {
      name: 'Ballista Squad',
      color: 'White',
      type: 'Creature — Human Rebel',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: '{X}{W}, {T}: Ballista Squad deals X damage to target attacking or blocking creature.',
      artist: 'Matthew D. Wilson',
      number: '8',
      price: 477,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129477&type=card',
      id: 'a69b404f-144a-5317-b10e-7d9dce135b24',
    },
    {
      name: 'Bandage',
      color: 'White',
      type: 'Instant',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: 'Prevent the next 1 damage that would be dealt to any target this turn.\nDraw a card.',
      artist: 'Rebecca Guay',
      number: '9',
      price: 106,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=132106&type=card',
      id: '6d268c95-c176-5766-9a46-c14f739aba1c',
    },
    {
      name: 'Beacon of Immortality',
      color: 'White',
      type: 'Instant',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: "Double target player's life total. Shuffle Beacon of Immortality into its owner's library.",
      artist: 'Rob Alexander',
      number: '10',
      price: 553,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=130553&type=card',
      id: '56f4935b-f6c5-59b9-88bf-9bcce20247ce',
    },
    {
      name: 'Benalish Knight',
      color: 'White',
      type: 'Creature — Human Knight',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: 'Flash (You may cast this spell any time you could cast an instant.)\nFirst strike (This creature deals combat damage before creatures without first strike.)',
      artist: 'Zoltan Boros & Gabor Szikszai',
      number: '11',
      price: 279,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=136279&type=card',
      id: '62365fbb-af07-5c2a-976d-e3092bdfc317',
    },
    {
      name: 'Cho-Manno, Revolutionary',
      color: 'White',
      type: 'Legendary Creature — Human Rebel',
      supertypes: 'Legendary',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: 'Prevent all damage that would be dealt to Cho-Manno, Revolutionary.',
      artist: 'Steven Belledin',
      number: '12',
      price: 554,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=130554&type=card',
      id: '81daea6a-2735-5a46-a2da-b65a2ad5738f',
    },
    {
      name: 'Condemn',
      color: 'White',
      type: 'Instant',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: "Put target attacking creature on the bottom of its owner's library. Its controller gains life equal to its toughness.",
      artist: 'Daren Bader',
      number: '13',
      price: 528,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=130528&type=card',
      id: '7fef665c-36a1-5f7a-9299-cf8938708710',
    },
    {
      name: 'Demystify',
      color: 'White',
      type: 'Instant',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: 'Destroy target enchantment.',
      artist: 'Christopher Rush',
      number: '14',
      price: 524,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129524&type=card',
      id: '2f9c211e-1869-5b3f-94ea-f73b7910a5af',
    },
    {
      name: 'Field Marshal',
      color: 'White',
      type: 'Creature — Human Soldier',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: 'Other Soldier creatures get +1/+1 and have first strike. (They deal combat damage before creatures without first strike.)',
      artist: 'Stephen Tappin',
      number: '15',
      price: 258,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135258&type=card',
      id: '668c64a2-cecb-5f48-af16-d7a64814d3e7',
    },
    {
      name: 'Ghost Warden',
      color: 'White',
      type: 'Creature — Spirit',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: '{T}: Target creature gets +1/+1 until end of turn.',
      artist: 'Ittoku',
      number: '16',
      price: 105,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=132105&type=card',
      id: 'd68306e2-9877-5987-84b3-12b8234c8eec',
    },
    {
      name: 'Glorious Anthem',
      color: 'White',
      type: 'Enchantment',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: 'Creatures you control get +1/+1.',
      artist: 'Kev Walker',
      number: '17',
      price: 572,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129572&type=card',
      id: '546eac7c-1424-597d-ac13-bf8558e88fe3',
    },
    {
      name: 'Hail of Arrows',
      color: 'White',
      type: 'Instant',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: 'Hail of Arrows deals X damage divided as you choose among any number of target attacking creatures.',
      artist: 'Anthony S. Waters',
      number: '18',
      price: 107,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=132107&type=card',
      id: 'c19bcfc2-fc10-5040-8239-1c193098df47',
    },
    {
      name: 'Heart of Light',
      color: 'White',
      type: 'Enchantment — Aura',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: 'Enchant creature (Target a creature as you cast this. This card enters the battlefield attached to that creature.)\nPrevent all damage that would be dealt to and dealt by enchanted creature.',
      artist: 'Luca Zontini',
      number: '19',
      price: 290,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=132090&type=card',
      id: '36fcaa1e-64e3-56e3-950c-907db167e41f',
    },
    {
      name: 'High Ground',
      color: 'White',
      type: 'Enchantment',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: 'Each creature you control can block an additional creature each combat.',
      artist: 'rk post',
      number: '20',
      price: 145,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=132145&type=card',
      id: '60f49caf-3583-5f85-b4b3-08dca73a8628',
    },
    {
      name: 'Honor Guard',
      color: 'White',
      type: 'Creature — Human Soldier',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: '{W}: Honor Guard gets +0/+1 until end of turn.',
      artist: 'Dan Dos Santos',
      number: '23',
      price: 595,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129595&type=card',
      id: '9bee1901-1125-5635-9e22-3b4f37989c37',
    },
    {
      name: 'Icatian Priest',
      color: 'White',
      type: 'Creature — Human Cleric',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: '{1}{W}{W}: Target creature gets +1/+1 until end of turn.',
      artist: 'Stephen Tappin',
      number: '24',
      price: 123,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=132123&type=card',
      id: 'cb865391-5b14-58ce-aa99-b36b83e6377f',
    },
    {
      name: 'Reviving Dose',
      color: 'White',
      type: 'Instant',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: 'You gain 3 life.\nDraw a card.',
      artist: 'D. Alexander Gregory',
      number: '34',
      price: 189,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=132089&type=card',
      id: '39b50224-8305-56dd-9849-09deecb07d20',
    },
    {
      name: 'Reya Dawnbringer',
      color: 'White',
      type: 'Legendary Creature — Angel',
      supertypes: 'Legendary',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: 'Flying\nAt the beginning of your upkeep, you may return target creature card from your graveyard to the battlefield.',
      artist: 'Matthew D. Wilson',
      number: '35',
      price: 384,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=106384&type=card',
      id: '6028cab2-0478-584b-a880-8174a88eb188',
    },
    {
      name: 'Righteousness',
      color: 'White',
      type: 'Instant',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: 'Target blocking creature gets +7/+7 until end of turn.',
      artist: 'Wayne England',
      number: '36',
      price: 552,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=130552&type=card',
      id: '9a14261a-b567-5429-a5ca-a913e15d8bf7',
    },
    {
      name: 'Samite Healer',
      color: 'White',
      type: 'Creature — Human Cleric',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: '{T}: Prevent the next 1 damage that would be dealt to any target this turn.',
      artist: 'Anson Maddocks',
      number: '38',
      price: 101,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=132101&type=card',
      id: 'a2be2e9b-5211-53e6-ac6a-abd65dbcac1d',
    },
    {
      name: "Serra's Embrace",
      color: 'White',
      type: 'Enchantment — Aura',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: 'Enchant creature\nEnchanted creature gets +2/+2 and has flying and vigilance.',
      artist: 'Zoltan Boros & Gabor Szikszai',
      number: '40',
      price: 214,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135214&type=card',
      id: 'fe9187fa-cd14-5618-9a62-bcf18b523d84',
    },
    {
      name: 'Academy Researchers',
      color: 'Blue',
      type: 'Creature — Human Wizard',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: 'When Academy Researchers enters the battlefield, you may put an Aura card from your hand onto the battlefield attached to Academy Researchers.',
      artist: 'Stephen Daniele',
      number: '63',
      price: 172,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=132072&type=card',
      id: 'b8a68840-4044-52c0-a14e-0a1c630ba42c',
    },
    {
      name: 'Air Elemental',
      color: 'Blue',
      type: 'Creature — Elemental',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: 'Flying',
      artist: 'Kev Walker',
      number: '64',
      price: 459,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129459&type=card',
      id: '76ddd7f5-1a84-55d5-98f5-4883c217e0d8',
    },
    {
      name: 'Ambassador Laquatus',
      color: 'Blue',
      type: 'Legendary Creature — Merfolk Wizard',
      supertypes: 'Legendary',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: '{3}: Target player mills three cards.',
      artist: 'Jim Murray',
      number: '65',
      price: 913,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129913&type=card',
      id: '29723d8d-34c9-5009-8b79-2c679e35f674',
    },
    {
      name: 'Aven Fisher',
      color: 'Blue',
      type: 'Creature — Bird Soldier',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: "Flying (This creature can't be blocked except by creatures with flying or reach.)\nWhen Aven Fisher dies, you may draw a card.",
      artist: 'Christopher Moeller',
      number: '68',
      price: 985,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=130985&type=card',
      id: '758df5d5-992f-5d30-b6bc-87cb1a0788ab',
    },
    {
      name: 'Aven Windreader',
      color: 'Blue',
      type: 'Creature — Bird Soldier Wizard',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: "Flying (This creature can't be blocked except by creatures with flying or reach.)\n{1}{U}: Target player reveals the top card of their library.",
      artist: 'Greg Hildebrandt',
      number: '69',
      price: 473,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129473&type=card',
      id: 'd833c453-58c5-5ff6-91b2-f526ca5f808a',
    },
    {
      name: 'Boomerang',
      color: 'Blue',
      type: 'Instant',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: "Return target permanent to its owner's hand.",
      artist: 'Arnie Swekel',
      number: '70',
      price: 494,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129494&type=card',
      id: '1aac00c8-3b6e-5bdd-9fde-6cfcbc7837c0',
    },
    {
      name: 'Cancel',
      color: 'Blue',
      type: 'Instant',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: 'Counter target spell.',
      artist: 'Mark Poole',
      number: '71',
      price: 882,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129882&type=card',
      id: 'cdc96814-2f52-5314-80ab-0cff2dcc5054',
    },
    {
      name: 'Cephalid Constable',
      color: 'Blue',
      type: 'Creature — Cephalid Wizard',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: "Whenever Cephalid Constable deals combat damage to a player, return up to that many target permanents that player controls to their owner's hand.",
      artist: 'Alan Pollack',
      number: '72',
      price: 261,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135261&type=card',
      id: '9af574e4-dc6e-5246-8fe7-fee6c4c77a76',
    },
    {
      name: 'Clone',
      color: 'Blue',
      type: 'Creature — Shapeshifter',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: 'You may have Clone enter the battlefield as a copy of any creature on the battlefield.',
      artist: 'Kev Walker',
      number: '73',
      price: 501,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129501&type=card',
      id: '8dfc67e9-8323-5d1f-9e25-9f9394abd5a0',
    },
    {
      name: 'Cloud Elemental',
      color: 'Blue',
      type: 'Creature — Elemental',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: 'Flying\nCloud Elemental can block only creatures with flying.',
      artist: 'Michael Sutfin',
      number: '74',
      price: 804,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129804&type=card',
      id: '596a7bd4-895b-5e7c-8124-373fd709444d',
    },
    {
      name: 'Cloud Sprite',
      color: 'Blue',
      type: 'Creature — Faerie',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: "Flying (This creature can't be blocked except by creatures with flying or reach.)\nCloud Sprite can block only creatures with flying.",
      artist: 'Mark Zug',
      number: '75',
      price: 269,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=132069&type=card',
      id: 'fdbec3b3-f6f2-5149-a70a-4f9d2622a87b',
    },
    {
      name: 'Counsel of the Soratami',
      color: 'Blue',
      type: 'Sorcery',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: 'Draw two cards.',
      artist: 'Randy Gallegos',
      number: '76',
      price: 757,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=134757&type=card',
      id: 'eb5c94c7-5494-5669-9c54-6f3672d65683',
    },
    {
      name: 'Crafty Pathmage',
      color: 'Blue',
      type: 'Creature — Human Wizard',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: "{T}: Target creature with power 2 or less can't be blocked this turn.",
      artist: 'Wayne England',
      number: '77',
      price: 758,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=134758&type=card',
      id: '8d5f87fd-7a87-572b-bdce-303effec6b92',
    },
    {
      name: 'Dehydration',
      color: 'Blue',
      type: 'Enchantment — Aura',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: "Enchant creature (Target a creature as you cast this. This card enters the battlefield attached to that creature.)\nEnchanted creature doesn't untap during its controller's untap step.",
      artist: 'Arnie Swekel',
      number: '78',
      price: 521,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129521&type=card',
      id: '5a50a7e8-2ed1-5e8a-8867-c96f1186bd47',
    },
    {
      name: 'Deluge',
      color: 'Blue',
      type: 'Instant',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: 'Tap all creatures without flying.',
      artist: 'Wayne England',
      number: '79',
      price: 223,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135223&type=card',
      id: 'a9a74d88-7663-5419-a74c-5a28e8642b4f',
    },
    {
      name: 'Denizen of the Deep',
      color: 'Blue',
      type: 'Creature — Serpent',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: "When Denizen of the Deep enters the battlefield, return each other creature you control to its owner's hand.",
      artist: 'Jim Pavelec',
      number: '80',
      price: 250,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135250&type=card',
      id: 'f4ee3e9e-21da-5a63-8278-3efa59da7df3',
    },
    {
      name: 'Discombobulate',
      color: 'Blue',
      type: 'Instant',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: 'Counter target spell. Look at the top four cards of your library, then put them back in any order.',
      artist: 'Alex Horley-Orlandelli',
      number: '81',
      price: 749,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=134749&type=card',
      id: 'e2066f75-65de-5254-82f2-8e1f969bf31b',
    },
    {
      name: 'Dreamborn Muse',
      color: 'Blue',
      type: 'Creature — Spirit',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: "At the beginning of each player's upkeep, that player mills X cards, where X is the number of cards in their hand.",
      artist: 'Kev Walker',
      number: '82',
      price: 246,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135246&type=card',
      id: '6f9ae90a-5638-5b88-a3d7-ccea4372eb79',
    },
    {
      name: 'Evacuation',
      color: 'Blue',
      type: 'Instant',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: "Return all creatures to their owners' hands.",
      artist: 'Franz Vohwinkel',
      number: '83',
      price: 541,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129541&type=card',
      id: '100f46ae-e457-5491-b5d1-66cd9284304c',
    },
    {
      name: 'Afflict',
      color: 'Black',
      type: 'Instant',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: 'Target creature gets -1/-1 until end of turn.\nDraw a card.',
      artist: 'Roger Raupp',
      number: '125',
      price: 206,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135206&type=card',
      id: '9acf4d13-d68f-5fec-93b4-caf0a14725a5',
    },
    {
      name: 'Agonizing Memories',
      color: 'Black',
      type: 'Sorcery',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: "Look at target player's hand and choose two cards from it. Put them on top of that player's library in any order.",
      artist: 'Adam Rex',
      number: '126',
      price: 228,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135228&type=card',
      id: '4429ce97-b78e-5bc4-bd34-a38b26794bdf',
    },
    {
      name: 'Ascendant Evincar',
      color: 'Black',
      type: 'Legendary Creature — Vampire Noble',
      supertypes: 'Legendary',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: "Flying (This creature can't be blocked except by creatures with flying or reach.)\nOther black creatures get +1/+1.\nNonblack creatures get -1/-1.",
      artist: 'Mark Zug',
      number: '127',
      price: 525,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=106525&type=card',
      id: 'bba43f4e-a9eb-5c89-8389-5935a1fbd8b3',
    },
    {
      name: 'Assassinate',
      color: 'Black',
      type: 'Sorcery',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: 'Destroy target tapped creature.',
      artist: 'Kev Walker',
      number: '128',
      price: 194,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135194&type=card',
      id: 'c6f3da33-27e8-51e4-9859-ef7cb3cdbe61',
    },
    {
      name: 'Beacon of Unrest',
      color: 'Black',
      type: 'Sorcery',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: "Put target artifact or creature card from a graveyard onto the battlefield under your control. Shuffle Beacon of Unrest into its owner's library.",
      artist: 'Alan Pollack',
      number: '129',
      price: 270,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135270&type=card',
      id: 'efdd5367-9393-54c1-a6b8-c7810ee87ed5',
    },
    {
      name: 'Bog Wraith',
      color: 'Black',
      type: 'Creature — Wraith',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: "Swampwalk (This creature can't be blocked as long as defending player controls a Swamp.)",
      artist: 'Daarken',
      number: '130',
      price: 491,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129491&type=card',
      id: 'ac084dab-6ac0-55fa-94b7-e009fede9012',
    },
    {
      name: "Hurkyl's Recall",
      color: 'Blue',
      type: 'Instant',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: 'Return all artifacts target player owns to their hand.',
      artist: 'Ralph Horsley',
      number: '88',
      price: 260,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135260&type=card',
      id: '5ac794d2-4c66-5332-afb1-54b24bc11823',
    },
    {
      name: 'Reminisce',
      color: 'Blue',
      type: 'Sorcery',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: 'Target player shuffles their graveyard into their library.',
      artist: 'Ralph Horsley',
      number: '99',
      price: 698,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129698&type=card',
      id: '4fa9bf42-9170-594e-bbf9-42111adea313',
    },
    {
      name: 'Remove Soul',
      color: 'Blue',
      type: 'Instant',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: 'Counter target creature spell.',
      artist: 'Adam Rex',
      number: '100',
      price: 699,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129699&type=card',
      id: 'f37b2caa-03c5-51ec-a02a-c2e5311a9fd5',
    },
    {
      name: 'Robe of Mirrors',
      color: 'Blue',
      type: 'Enchantment — Aura',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: "Enchant creature (Target a creature as you cast this. This card enters the battlefield attached to that creature.)\nEnchanted creature has shroud. (It can't be the target of spells or abilities.)",
      artist: 'Christopher Moeller',
      number: '101',
      price: 764,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=134764&type=card',
      id: '9626b37d-3a04-5cd6-a636-943981354e2b',
    },
    {
      name: 'Rootwater Commando',
      color: 'Blue',
      type: 'Creature — Merfolk',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: "Islandwalk (This creature can't be blocked as long as defending player controls an Island.)",
      artist: 'Mark Tedin',
      number: '102',
      price: 733,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129733&type=card',
      id: 'f1eba89f-dd82-5843-80a9-e9b2cd3a6037',
    },
    {
      name: 'Rule of Law',
      color: 'White',
      type: 'Enchantment',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: "Each player can't cast more than one spell each turn.",
      artist: 'Scott M. Fischer',
      number: '37',
      price: 291,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=136291&type=card',
      id: 'eee00aa2-c730-5ff1-84a9-51d95a9fe180',
    },
    {
      name: 'Rootwater Matriarch',
      color: 'Blue',
      type: 'Creature — Merfolk',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: '{T}: Gain control of target creature for as long as that creature is enchanted.',
      artist: 'Daren Bader',
      number: '103',
      price: 252,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135252&type=card',
      id: 'fc96da15-9362-585a-b555-f7a7e5480e8b',
    },
    {
      name: 'Sage Owl',
      color: 'Blue',
      type: 'Creature — Bird',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: 'Flying\nWhen Sage Owl enters the battlefield, look at the top four cards of your library, then put them back in any order.',
      artist: 'Mark Brill',
      number: '104',
      price: 217,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135217&type=card',
      id: 'cdf65c48-2ac8-522a-bbcf-2f8165187a18',
    },
    {
      name: 'Scalpelexis',
      color: 'Blue',
      type: 'Creature — Beast',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: "Flying (This creature can't be blocked except by creatures with flying or reach.)\nWhenever Scalpelexis deals combat damage to a player, that player exiles the top four cards of their library. If two or more of those cards have the same name, repeat this process.",
      artist: 'Mark Tedin',
      number: '105',
      price: 818,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=130818&type=card',
      id: 'd5124438-a5d4-5b3b-88af-d179f4b9c9af',
    },
    {
      name: 'Serra Angel',
      color: 'White',
      type: 'Creature — Angel',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: 'Flying, vigilance',
      artist: 'Greg Staples',
      number: '39',
      price: 726,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129726&type=card',
      id: 'be665b02-1cf2-50c6-8861-85da921bc853',
    },
    {
      name: 'Sea Monster',
      color: 'Blue',
      type: 'Creature — Serpent',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: "Sea Monster can't attack unless defending player controls an Island.",
      artist: 'Brian Despain',
      number: '106',
      price: 719,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129719&type=card',
      id: '9db6f50d-3242-5cbc-9f71-45477f4967df',
    },
    {
      name: 'Shimmering Wings',
      color: 'Blue',
      type: 'Enchantment — Aura',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: "Enchant creature (Target a creature as you cast this. This card enters the battlefield attached to that creature.)\nEnchanted creature has flying. (It can't be blocked except by creatures with flying or reach.)\n{U}: Return Shimmering Wings to its owner's hand.",
      artist: 'Carl Critchlow',
      number: '107',
      price: 553,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129553&type=card',
      id: 'a122a3b0-b686-5b96-a02c-926423c65b13',
    },
    {
      name: 'Sift',
      color: 'Blue',
      type: 'Sorcery',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: 'Draw three cards, then discard a card.',
      artist: 'Jeremy Jarvis',
      number: '108',
      price: 217,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=136217&type=card',
      id: '39adc884-8e24-572d-ad54-74561b1cb139',
    },
    {
      name: 'Sky Weaver',
      color: 'Blue',
      type: 'Creature — Metathran Wizard',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: "{2}: Target white or black creature gains flying until end of turn. (It can't be blocked except by creatures with flying or reach.)",
      artist: 'Christopher Moeller',
      number: '109',
      price: 998,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=130998&type=card',
      id: '18db55ad-e62f-5c76-a6b8-743378d6ea38',
    },
    {
      name: 'Mortivore',
      color: 'Black',
      type: 'Creature — Lhurgoyf',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: "Mortivore's power and toughness are each equal to the number of creature cards in all graveyards.\n{B}: Regenerate Mortivore.",
      artist: 'Anthony S. Waters',
      number: '161',
      price: 648,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129648&type=card',
      id: '889dbfab-bcc2-5a94-ba57-01d229c6dccd',
    },
    {
      name: 'Nomad Mythmaker',
      color: 'White',
      type: 'Creature — Human Nomad Cleric',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: '{W}, {T}: Put target Aura card from a graveyard onto the battlefield under your control attached to a creature you control.',
      artist: 'Darrell Riche',
      number: '30',
      price: 547,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=130547&type=card',
      id: '5d53a06b-68a0-5d1a-a1a5-a676f16c23dd',
    },
    {
      name: 'Paladin en-Vec',
      color: 'White',
      type: 'Creature — Human Knight',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: "First strike, protection from black and from red (This creature deals combat damage before creatures without first strike. It can't be blocked, targeted, dealt damage, or enchanted by anything black or red.)",
      artist: 'Dave Kendall',
      number: '32',
      price: 668,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129668&type=card',
      id: '214dbfe9-0f16-5b6b-be30-8771192a89ec',
    },
    {
      name: 'Peek',
      color: 'Blue',
      type: 'Instant',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: "Look at target player's hand.\nDraw a card.",
      artist: 'Adam Rex',
      number: '94',
      price: 903,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=130903&type=card',
      id: '284ed7cc-8917-5005-bfa9-e7c61b1fb85e',
    },
    {
      name: 'Phantom Warrior',
      color: 'Blue',
      type: 'Creature — Illusion Warrior',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: "Phantom Warrior can't be blocked.",
      artist: 'Greg Staples',
      number: '96',
      price: 364,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=132064&type=card',
      id: '8d5006e3-45cb-5d9f-896d-83a22d86d53d',
    },
    {
      name: 'Plagiarize',
      color: 'Blue',
      type: 'Instant',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: 'Until end of turn, if target player would draw a card, instead that player skips that draw and you draw a card.',
      artist: 'Jeremy Jarvis',
      number: '97',
      price: 883,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129883&type=card',
      id: '5a1f3fc3-e970-5408-94ef-e7c78e57000b',
    },
    {
      name: 'Consume Spirit',
      color: 'Black',
      type: 'Sorcery',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: 'Spend only black mana on X.\nConsume Spirit deals X damage to any target and you gain X life.',
      artist: 'Matt Thompson',
      number: '131',
      price: 505,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129505&type=card',
      id: '26180f1b-41a1-5fa5-9f6b-39ee08a1a203',
    },
    {
      name: 'Contaminated Bond',
      color: 'Black',
      type: 'Enchantment — Aura',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: 'Enchant creature (Target a creature as you cast this. This card enters the battlefield attached to that creature.)\nWhenever enchanted creature attacks or blocks, its controller loses 3 life.',
      artist: 'Thomas M. Baxa',
      number: '132',
      price: 590,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129590&type=card',
      id: '2562f5f1-4de2-5834-a9ff-99092380d910',
    },
    {
      name: 'Cruel Edict',
      color: 'Black',
      type: 'Sorcery',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: 'Target opponent sacrifices a creature.',
      artist: 'Michael Sutfin',
      number: '133',
      price: 514,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129514&type=card',
      id: 'e77dbe8c-5878-5881-b5f3-8203af673278',
    },
    {
      name: 'Deathmark',
      color: 'Black',
      type: 'Sorcery',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: 'Destroy target green or white creature.',
      artist: 'Jeremy Jarvis',
      number: '134',
      price: 910,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129910&type=card',
      id: '7069fe50-d855-59ea-b445-e8068cda7559',
    },
    {
      name: 'Diabolic Tutor',
      color: 'Black',
      type: 'Sorcery',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: 'Search your library for a card, put that card into your hand, then shuffle.',
      artist: 'Greg Staples',
      number: '135',
      price: 525,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129525&type=card',
      id: 'e9435188-40bd-54c7-938f-798459b038ed',
    },
    {
      name: 'Distress',
      color: 'Black',
      type: 'Sorcery',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: 'Target player reveals their hand. You choose a nonland card from it. That player discards that card.',
      artist: 'Michael Sutfin',
      number: '136',
      price: 219,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135219&type=card',
      id: '77ce01d6-3609-519e-a0d4-6ad6770c45e4',
    },
    {
      name: 'Doomed Necromancer',
      color: 'Black',
      type: 'Creature — Human Cleric Mercenary',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: '{B}, {T}, Sacrifice Doomed Necromancer: Return target creature card from your graveyard to the battlefield.',
      artist: 'Volkan Baǵa',
      number: '137',
      price: 880,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129880&type=card',
      id: '49f64f3e-f0ff-5d4c-a730-5ea919857d82',
    },
    {
      name: 'Dross Crocodile',
      color: 'Black',
      type: 'Creature — Zombie Crocodile',
      rarity: 'Common',
      set: 'Tenth Edition',
      artist: 'Carl Critchlow',
      number: '138',
      price: 216,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135216&type=card',
      id: 'fea2ad06-355d-5a9a-822d-66275d89cad9',
    },
    {
      name: 'Drudge Skeletons',
      color: 'Black',
      type: 'Creature — Skeleton',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: "{B}: Regenerate Drudge Skeletons. (The next time this creature would be destroyed this turn, it isn't. Instead tap it, remove all damage from it, and remove it from combat.)",
      artist: 'Jim Nelson',
      number: '139',
      price: 529,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129529&type=card',
      id: '2d080e75-7e1b-5f75-9c8f-18d02a4710dd',
    },
    {
      name: 'Dusk Imp',
      color: 'Black',
      type: 'Creature — Imp',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: 'Flying',
      artist: 'Pete Venters',
      number: '140',
      price: 490,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129490&type=card',
      id: '42022e6f-e123-54a6-84df-ec826b13f5be',
    },
    {
      name: 'Essence Drain',
      color: 'Black',
      type: 'Sorcery',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: 'Essence Drain deals 3 damage to any target and you gain 3 life.',
      artist: 'Jim Nelson',
      number: '141',
      price: 191,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135191&type=card',
      id: 'd38298f2-29e8-57b0-b978-140aa2171cce',
    },
    {
      name: 'Fear',
      color: 'Black',
      type: 'Enchantment — Aura',
      rarity: 'Common',
      set: 'Tenth Edition',
      text: "Enchant creature (Target a creature as you cast this. This card enters the battlefield attached to that creature.)\nEnchanted creature has fear. (It can't be blocked except by artifact creatures and/or black creatures.)",
      artist: 'Adam Rex',
      number: '142',
      price: 544,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129544&type=card',
      id: 'b159e707-915c-5940-bd70-7f0416cc8def',
    },
    {
      name: 'Hidden Horror',
      color: 'Black',
      type: 'Creature — Horror',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: 'When Hidden Horror enters the battlefield, sacrifice it unless you discard a creature card.',
      artist: 'Brom',
      number: '149',
      price: 234,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135234&type=card',
      id: '6d030b32-0534-55c9-9c40-00bb59d4e164',
    },
    {
      name: 'Nantuko Husk',
      color: 'Black',
      type: 'Creature — Zombie Insect',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: 'Sacrifice a creature: Nantuko Husk gets +2/+2 until end of turn.',
      artist: 'Carl Critchlow',
      number: '162',
      price: 653,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129653&type=card',
      id: '60122d6f-448b-5df8-ac2a-8f5a1e841278',
    },
    {
      name: 'Nekrataal',
      color: 'Black',
      type: 'Creature — Human Assassin',
      rarity: 'Uncommon',
      set: 'Tenth Edition',
      text: "First strike\nWhen Nekrataal enters the battlefield, destroy target nonartifact, nonblack creature. That creature can't be regenerated.",
      artist: 'Christopher Moeller',
      number: '163',
      price: 658,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129658&type=card',
      id: 'f560811b-3c5d-5929-8b17-e9ae8730cec1',
    },
    {
      name: 'Nightmare',
      color: 'Black',
      type: 'Creature — Nightmare Horse',
      rarity: 'Rare',
      set: 'Tenth Edition',
      text: "Flying (This creature can't be blocked except by creatures with flying or reach.)\nNightmare's power and toughness are each equal to the number of Swamps you control.",
      artist: 'Carl Critchlow',
      number: '164',
      price: 659,
      imageUrl:
        'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129659&type=card',
      id: '5bd291f0-560a-5046-bd07-a91bd3004f2d',
    },
  ];

  addItem(item: string) {
    this.items.push(item);
    this.item = '';
  }

  deleteItem(index: number) {
    this.items.splice(index, 1);
  }

  deleteAll(): void {
    this.items = [];
  }
}
